/**
 * Generates `src/lib/us-map-data.ts` from the US Atlas topology.
 *
 * Source: us-atlas@3 `states-albers-10m.json` (https://github.com/topojson/us-atlas),
 * itself derived from the U.S. Census Bureau's public-domain cartographic
 * boundary files, pre-projected to a 975x610 Albers USA frame with Alaska and
 * Hawaii insets. This script is the committed provenance for every coordinate
 * in the generated file: the figure on the front page is drawn from Census
 * geometry, not from anything hand-placed.
 *
 * Usage:
 *   curl -sL -o /tmp/us-albers.json \
 *     "https://cdn.jsdelivr.net/npm/us-atlas@3/states-albers-10m.json"
 *   node scripts/generate-us-map.mjs /tmp/us-albers.json
 *   npx biome check --write src/lib/us-map-data.ts
 *
 * No dependencies. The TopoJSON decoding below is the standard arc scheme:
 * quantized delta-encoded arcs, negative index = reversed complement.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const source = process.argv[2]
if (!source) {
  console.error('usage: node scripts/generate-us-map.mjs <states-albers-10m.json>')
  process.exit(1)
}

const topo = JSON.parse(readFileSync(source, 'utf8'))
const { scale, translate } = topo.transform

/** Decode one arc into absolute [x, y] points. */
function decodeArc(arc) {
  let x = 0
  let y = 0
  return arc.map(([dx, dy]) => {
    x += dx
    y += dy
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]]
  })
}

const arcs = topo.arcs.map(decodeArc)

/** Stitch arc indices into one ring of points. */
function ring(indices) {
  const points = []
  for (const index of indices) {
    const arc = index >= 0 ? arcs[index] : [...arcs[~index]].reverse()
    // Consecutive arcs share their join point; drop the duplicate.
    for (const p of points.length === 0 ? arc : arc.slice(1)) points.push(p)
  }
  return points
}

const r1 = (n) => Math.round(n * 10) / 10

function ringPath(points) {
  let d = ''
  let last = null
  for (const [x, y] of points) {
    const px = r1(x)
    const py = r1(y)
    if (last !== null && px === last[0] && py === last[1]) continue
    d += `${last === null ? 'M' : 'L'}${px} ${py}`
    last = [px, py]
  }
  return `${d}Z`
}

/** Signed area and centroid of one ring (shoelace). */
function measure(points) {
  let area = 0
  let cx = 0
  let cy = 0
  for (let i = 0; i < points.length; i++) {
    const [x0, y0] = points[i]
    const [x1, y1] = points[(i + 1) % points.length]
    const cross = x0 * y1 - x1 * y0
    area += cross
    cx += (x0 + x1) * cross
    cy += (y0 + y1) * cross
  }
  area /= 2
  return { area: Math.abs(area), cx: cx / (6 * area), cy: cy / (6 * area) }
}

/** USPS code per Census state name. Only what the atlas contains. */
const POSTAL = {
  Alabama: 'AL',
  Alaska: 'AK',
  Arizona: 'AZ',
  Arkansas: 'AR',
  California: 'CA',
  Colorado: 'CO',
  Connecticut: 'CT',
  Delaware: 'DE',
  'District of Columbia': 'DC',
  Florida: 'FL',
  Georgia: 'GA',
  Hawaii: 'HI',
  Idaho: 'ID',
  Illinois: 'IL',
  Indiana: 'IN',
  Iowa: 'IA',
  Kansas: 'KS',
  Kentucky: 'KY',
  Louisiana: 'LA',
  Maine: 'ME',
  Maryland: 'MD',
  Massachusetts: 'MA',
  Michigan: 'MI',
  Minnesota: 'MN',
  Mississippi: 'MS',
  Missouri: 'MO',
  Montana: 'MT',
  Nebraska: 'NE',
  Nevada: 'NV',
  'New Hampshire': 'NH',
  'New Jersey': 'NJ',
  'New Mexico': 'NM',
  'New York': 'NY',
  'North Carolina': 'NC',
  'North Dakota': 'ND',
  Ohio: 'OH',
  Oklahoma: 'OK',
  Oregon: 'OR',
  Pennsylvania: 'PA',
  'Rhode Island': 'RI',
  'South Carolina': 'SC',
  'South Dakota': 'SD',
  Tennessee: 'TN',
  Texas: 'TX',
  Utah: 'UT',
  Vermont: 'VT',
  Virginia: 'VA',
  Washington: 'WA',
  'West Virginia': 'WV',
  Wisconsin: 'WI',
  Wyoming: 'WY',
  'Puerto Rico': 'PR',
}

const states = []
for (const geometry of topo.objects.states.geometries) {
  const name = geometry.properties.name
  const id = POSTAL[name]
  if (!id) {
    console.error(`no postal code for "${name}", skipped`)
    continue
  }
  const polygons = geometry.type === 'Polygon' ? [geometry.arcs] : geometry.arcs
  let d = ''
  let best = null
  for (const polygon of polygons) {
    for (const indices of polygon) {
      const points = ring(indices)
      d += ringPath(points)
      const m = measure(points)
      if (best === null || m.area > best.area) best = m
    }
  }
  states.push({ id, name, d, cx: r1(best.cx), cy: r1(best.cy) })
}
states.sort((a, b) => (a.id < b.id ? -1 : 1))

const here = dirname(fileURLToPath(import.meta.url))
const out = join(here, '..', 'src', 'lib', 'us-map-data.ts')

const body = `/**
 * GENERATED by scripts/generate-us-map.mjs. Do not edit by hand.
 *
 * Geometry: US Atlas states-albers-10m (topojson/us-atlas), derived from the
 * U.S. Census Bureau's public-domain cartographic boundary files, pre-projected
 * to a 975x610 Albers USA frame with Alaska and Hawaii inset. \`cx\`/\`cy\` is
 * the centroid of each state's largest ring, used as the anchor publishers'
 * marks cluster around.
 */

export const US_MAP_VIEWBOX = '0 0 975 610'

export interface StateShape {
  /** USPS code. */
  id: string
  name: string
  /** SVG path in the 975x610 frame. */
  d: string
  cx: number
  cy: number
}

export const US_STATES: readonly StateShape[] = [
${states
  .map(
    (s) =>
      `  { id: '${s.id}', name: ${JSON.stringify(s.name)}, cx: ${s.cx}, cy: ${s.cy}, d: '${s.d}' },`,
  )
  .join('\n')}
]
`
writeFileSync(out, body)
process.stdout.write(
  `wrote ${out}: ${states.length} states, ${(body.length / 1024).toFixed(1)}KB\n`,
)
